### List people
GET http://localhost:3001/api/persons

### Get person by id
GET http://localhost:3001/api/persons/2

### Delete person by id
DELETE http://localhost:3001/api/persons/2

### Add a new person
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Alice",
  "number": "1-800-333-4444"
}

### Unknown endpoint middleware
GET http://localhost:3001/api/notfound

###